app/models.py
from app import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User (UserMixin,db.Model):
    __tablename__ = 'user'

    
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))
    pitches = db.relationship('Pitch',backref = 'user',lazy = 'dynamic')
    comments = db.relationship('Comments',backref='user',lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.password_hash, password)
        

    def __repr__(self):
        return f'User {self.username}'



class Pitch(db.Model):
     __tablename__ = 'pitches'

     id = db.Column(db.Integer,primary_key = True)
     pitch  = db.Column(db.String(255))
     pitch_content = db.Column(db.String())
     pitch_category =  db.Column(db.String(255))
     users_id = db.Column(db.Integer,db.ForeignKey("user.id"))
     upvotes = db.Column(db.Integer)
     downvotes = db.Column(db.Integer)
     comments = db.relationship('Comments',backref =  'pitch_id',lazy = "dynamic")
     
     
     
     
     def save_pitch(self):
         db.session.add(self)
         db.session.commit()

     @classmethod
     def get_pitch(cls,id):
        pitch = Pitch.query.filter_by(id=id).first()
        return pitch
     
     @classmethod
     def get_pitches(cls,pitch_category):
        pitches = Pitch.query.filter_by(pitch_category=pitch_category).all()
        return pitches
         

class Comments(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    comment = db.Column(db.String())
    pitch = db.Column(db.Integer,db.ForeignKey("pitches.id"))
    user_id = db.Column(db.Integer,db.ForeignKey("user.id"))
    

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,pitch):
        comments = Comments.query.filter_by(pitch_id=pitch).all()
        return comments  
     
    

        

     
     
     
         

    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField, SelectField
from wtforms.validators import Required


class PitchForm(FlaskForm):

    pitch = TextAreaField('Pitch:',validators = [Required()])
    category = SelectField('Type',choices=[('business','Business pitch'),('science','Science pitch'),('life','Life pitch')],validators=[Required()])
    submit = SubmitField('Submit')
    
    
class UpdateProfile(FlaskForm):
    post = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class CommentsForm(FlaskForm):
    text = TextAreaField('Leave a comment:',validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()


def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    
    

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    #importing blue print
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # configure UploadSet
    configure_uploads(app,photos)

    

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views, error

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import User, Pitch, Comments
from flask_login import login_required, current_user
from .forms import PitchForm, UpdateProfile, CommentsForm
from .. import db,photos


@main.route('/')
def index():
    '''
    function to display pitches
    '''
    #Getting pitches from different categories
    business_pitches = Pitch.get_pitches('business')
    science_pitches = Pitch.get_pitches('science')
    life_pitches = Pitch.get_pitches('life')

    
   
    return render_template('index.html', business = business_pitches, science = science_pitches, life = life_pitches )
    
@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.post = form.post.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
        return redirect(url_for('main.profile',uname=uname))

@main.route('/pitch/new/', methods = ['GET','POST'])
@login_required
def add_pitch():
    form = PitchForm()
    if form.validate_on_submit():
        pitch = form.pitch.data
        category = form.category.data
        new_pitch = Pitch(pitch_content = pitch,pitch_category = category,user = current_user, upvotes=0, downvotes=0)
        new_pitch.save_pitch()
        return redirect(url_for('.index'))

    title = 'One Minute pitch'
    return render_template('add_pitch.html',title = title, pitch_form=form)

@main.route('/pitch/<int:id>', methods = ['GET','POST'])
def pitch(id):
    pitch = Pitch.get_pitch(id)
    

    if request.args.get("upvote"):
        pitch.upvotes += 1

        db.session.add(pitch)
        db.session.commit()

        return redirect("/pitch/{pitch_id}".format(pitch_id=pitch.id)) 

    elif request.args.get("downvote"):
        pitch.downvotes+=1

        db.session.add(pitch)
        db.session.commit()

        return redirect("/pitch/{pitch_id}".format(pitch_id=pitch.id))

    comment_form = CommentsForm()
    if comment_form.validate_on_submit():
        comment = comment_form.text.data

        new_comment = Comments(comment = comment,user = current_user,pitch_id = pitch)

        new_comment.save_comment()
    comments = Comments.get_comments(pitch)

    return render_template("pitch.html", pitch = pitch, comment_form = comment_form, comments = comments)












       






  

app/templates/add_pitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">

        <div class="col-md-8">
            <h1> Present a pitch</h1>
        </div>

        <div class="col-md-4">

            {{ wtf.quick_form(pitch_form) }}
             
        </div>

    </div>

{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html' %}
<!-- Navbar block -->
{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}




    
    {% block content %}
    <div class ="categories">
            <div class='container card  block' >
    <h3 >Business</h3>
    <ul>
        {{ macro.displayPitchesList(business)}}
    </ul>
    </div>

   
            <div class='container card  block' >

    <h3 > Science </h3>
    <ul>
        {{ macro.displayPitchesList(science)}}
    </ul>
    </div>
    
   
            <div class='container card  block' >

    <h3>Life</h3>
    <ul>
        {{ macro.displayPitchesList(life)}}
    </ul>
    
    </div>
    </div>
    <style>
        .categories {
            flex-direction: row;
            margin-left:35%;
            
            

        }

        body{
            background-color: rgb(19, 235, 235); 
        }
        h3{
            color: rgb(19, 41, 243);
        }
    </style>
    {% endblock%}  

app/templates/macros.html
{% macro displayPitchesList(pitch_list) %}

    {% for pitch in pitch_list %}
        <div class="col-xs-12 col-sm-4 col-md-2 col-lg-2 panel bg">
            <p>{{ pitch_content }}</p>
            
            <p class="text-center">{{pitch.pitch_content}}</p>
            
            <h5 class="text-center">Published by: {{pitch.user.username}}</h5>
            <li class="text-center">
                    <a href="/pitch/{{pitch.id}}">View pitch</a>
                </li>
        </div>

    {% endfor %}

{% endmacro %}
{% macro displayComments(comments_list) %}
    {% for comment in comments_list %}
        <div class="col-md-12">
            <h5>{{comment.user.username}}</h5>
            <p>{{comment.comment}}</p>
        </div>
    {% endfor %}
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"><h3> HOME </h3></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/"><h3>PITCHES</h3></a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if current_user.is_authenticated %}
                        <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                        <li style="color:white;padding:15px;">{{current_user.username}}</li>
                        <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                        {% else %}
                        <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                        {%endif%}
                      </ul>

            </div>

        </div>
    </div>

app/templates/pitch.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% import "bootstrap/wtf.html" as wtf %}

<!DOCTYPE html>
<html>
        
        
        
        {% block content %}
        <div class="container">
            <div class="row">
                <p>{{pitch.pitch_content}}</p>
                <span>
                <p>Posted on {{date}} by {{pitch.user.username| capitalize}}</p>
                <a href="/pitch/{{pitch.id}}?upvote=1">
                <i class="material-icons"></i>
                    <i class="material-icons">Up_Vote</i>
                </a>{{pitch.upvotes}} <a href="/pitch/{{pitch.id}}?downvote=1">
                    <i class="material-icons">Down_Vote</i>
                </a>{{pitch.downvotes}}</span>
                 <a class="ratings" href="/pitch/new/"> Add a new pitch</a>
            </div>
            <div class="row">
                <hr>
                {% if current_user.is_authenticated %}
                    {{ wtf.quick_form(comment_form) }}
                {% endif %}
                <h3>Comments</h4>
                {{macro.displayComments(comments)}}
            </div>
        </div>
        {% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">
      {% if user == current_user %}
      <a href="{{url_for('main.update_profile',uname=user.username)}}" class = "btn btn-secondary"><h2>Edit profile</h2></a>
  {% endif %}

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}

   
  </div>
  <br>
  <br>
        {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <br>
      <br>
      <input type="submit" class = "btn btn-primary">
    </form>
      {% endif %}
  </div>
  <br>
  <br>
  <div>
      <a class="ratings" href="/pitch/new/"> Present your pitch</a>
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}